### ISSUE TITLE
Constant 503 errors from the proxy

### ISSUE THREAD

**Issue by ypatent** [launchdarkly/ld-relay#101]
**Describe the bug**
My app is using the ruby gem to connect to LD. When working with the ld service directly, everything works as expected. When i add the proxy in the middle (running it with a docker container), the proxy returns 503 errors with the message "Event proxy is not enabled for this environment".
Anything that im missing in the config?

**To reproduce**
Run a ruby application configured to work with the proxy's urls. use the sdk key for one of your envs.
run the command in the docker with 
`--from-env LD_ENV_your_env=sdkkey`

**Expected behavior**
No errors should be returned by the process

**Relay version**
5.12.0

**Language version, developer tools**
Ruby 2.4.1

**OS/platform**
OSX Mojave, using RubyMine

**Comment by sumuis** [comment]
...

**Comment by eli-darkly** [comment]
Yes, you're missing something in the config. If you want analytics events to be sent through the Relay Proxy, rather than directly to the LD events service, then you need to enable event proxying as described in [the configuration docs](https://github.com/launchdarkly/ld-relay/blob/v5/README.md#file-section-events). That's not enabled by default, as the error message indicates.

On the other hand, if you _don't_ want that, and you want the SDK to send events directly to LD instead, then you need to _not_ be setting the events URI in the SDK configuration to point to the Relay Proxy as I presume you're currently doing.

**Comment by ypatent** [comment]
indeed, the conf was missing.
thanks
