### ISSUE TITLE
Allow using Environment ID instead of SDK key in Authorization header for server routes

### ISSUE THREAD

**Issue by gaiazov** [launchdarkly/ld-relay#116]
**Is your feature request related to a problem? Please describe.**
At Appian we plan to integrate LaunchDarkly into our product using the relay proxy. Customers of Appian have their own stack, so we have several thousand servers running for our customers. We plan to connect all of them to shared instances of relay proxy, and we are using the Java server SDK exclusively.

Our issue arises when we want to rotate our server SDK keys. If we want to rotate the key in our proxy we would also need to update the key in the Java SDK. Since the Java SDK is a dependency inside of our web servers, in order to update our key in the client it would require a web server restart in the running instance of Appian. We cannot restart a production Appian web server without our customer’s consent, since our customer’s application would experience downtime. This means that rotating an SDK key would require a significant amount of work.  

**Describe the solution you'd like**
Looking at the source code for the relay proxy, it appears that the SDK key that the Java Server SDK provides is only used to identify which environment should be used. Instead of using the SDK key, we would like to being able to identify the environment through a different key such as the environment ID. It appears that this is the existing functionality for the client side Javascript SDK. 

If we are able to change this behavior then we could rotate the keys for our proxy server without needing the web server restart from our customer’s application, and without having to manage additional secrets (SDK key) inside our production web servers.

**Describe alternatives you've considered**
We condisdered using the Daemon mode, but it looks like we'd be giving up some functionality compared to using proxy mode. Alternatively, if the proxy is only configured with a single mode, perhaps no key should be needed at all.

**Comment by bwoskow-ld** [comment]
Hi @gaiazov ,

I'm not sure if you are on LaunchDarkly's Enterprise plan, but if you are, you should take advantage of Relay's [automatic configuration feature](https://docs.launchdarkly.com/home/advanced/relay-proxy-enterprise/automatic-configuration). This feature will get you exactly what you're looking for -- the ability for Relay to automatically detect when an SDK key is rotated, among other actions, so that Relay can update itself to support traffic with the new SDK key without needing any downtime.

As for updating the server routes to access environment IDs instead of SDK keys -- that's not a change we're able to accept. The server routes return the entire flag ruleset including targeting rules which may expose business logic. As a result an SDK key is required to utilize these routes. SDK keys are considered sensitive and are only known to your team -- not to your customers -- whereas environment IDs are not sensitive and can easily be found by customers if you are also using a client-side SDK for your project such as the JavaScript SDK. [This documentation](https://docs.launchdarkly.com/sdk/concepts/client-side-server-side) describes some of the security differences and their implications between our server-side and client-side SDKs, and our SDK keys and client-side IDs.

Additionally, Relay's routes are meant to replicate the behavior of the corresponding routes backed by LaunchDarkly's servers and those routes require SDK keys to be provided for the reasons I stated above.

I'll have to decline [your pull request](https://github.com/launchdarkly/ld-relay/pull/117). Let me known if this sufficiently answers your questions.

Cheers,
Ben

**Comment by gaiazov** [comment]
@bwoskow-ld thank you so much for a quick response! We are on Enterprise plan, and the automatic configuration feature does look interesting.

Thank you for your explanation, it makes sense. Now I have a question about the automated configuration - it doesn't seem to eliminate the need to rotate the keys in the server SDKs. Because that's our issue. Eventually we will have _thousands_ server SDKs running, due to our infrastructure. Having to rotate keys in so many server SDKs is something we'd like to avoid, if possible.

**Comment by bwoskow-ld** [comment]
Great, I'm glad that the automatic configuration feature will help resolve the issue.

I want to stress again that SDK keys are meant to be sensitive and should be treated as such. As a result, if you're properly storing it and transmitting it, you shouldn't need to rotate your SDK keys very often if ever. However, when it gets exposed, yes you will need to update all of your server-side SDK instances to use the new key, and you'll need to do a rolling redeploy of your application to allow the server-side SDKs to restart without incurring any downtime in your application. You'd need to do this whether those SDKs are connecting to the Relay Proxy or directly to LaunchDarkly.

The exact details of how you can efficiently rotate an SDK key depends on your application's infrastructure and tech stack. For example if you are using configuration-as-code (e.g. with Terraform) then you can update the SDK key in a single place and re-provision your application instances through Terraform.

I'm going to close this issue as the original Relay Proxy request has been addressed. If you want to discuss anything further, feel free to reach out to support@launchdarkly.com.
