### ISSUE TITLE
Exposing more metrics

### ISSUE THREAD

**Issue by absartaqvi** [launchdarkly/ld-relay#120]
I understand that the relay proxy exposes these metrics as documented [here](https://github.com/launchdarkly/ld-relay/blob/v6/docs/metrics.md):

- connections
- newconnections
- requests

We do have the above metrics reported. But if my reading of the [relay proxy monitoring](https://docs.launchdarkly.com/home/advanced/relay-proxy/monitoring#monitoring-the-relay-proxys-performance) is correct, then we should be able to monitor CPU and memory utilizations too. So my query is twofold:

1. Can you help expose memory and CPU utilisation statistics?
2. Where can I read more about the above three metrics? We are in demo/trial phase, so a more in-depth understanding would help.

**Comment by eli-darkly** [comment]
The docs page you linked to is simply suggesting some standard types of monitoring that can be done on any process, using any number of standard monitoring tools. There is no special functionality in the Relay Proxy for monitoring its own CPU usage or memory usage, because the tools for monitoring those things with any application work independently of the application and do not care about what the application is or how it works. What tools you would use for this are entirely dependent on your operating system or hosting environment.

**Comment by absartaqvi** [comment]
@eli-darkly thanks for the prompt response. I was expecting that Go SDK may have those metrics readily available than for us to tweak the relay OS.

If I can follow up on the second question/request: can you help with better understanding the currently three reported metrics: `connections`, `newconnections` and `requests`? For example, I have a web application running with an LD sidecar. The app has one environment, so it'd have one streaming connection to the LD servers right? 1 is reflected in the metrics. I'm puzzled about how the `newconnections` and `requests` metrics work.

**Comment by eli-darkly** [comment]
`connections`: The number of connections to LD that are currently active, so in your case, 1.

`newconnections`: The cumulative number of connections that have been made since Relay started up. So, if the streaming connection is broken and restarted, `connections` will go down by 1 and then back up to the previous number, while `newconnections` will go up by 1.

`requests`: The cumulative number of requests that Relay has received from clients.

**Comment by eli-darkly** [comment]
> I was expecting that Go SDK may have those metrics readily available than for us to tweak the relay OS

I'm really not sure what you mean. It's normal for monitoring tools to be OS-specific because the method of determining things like CPU usage is OS-specific. That's not a matter of "tweaking the OS", it simply means that for any given OS there are particular tools you can use. For the LaunchDarkly Go SDK, or a Go-based application like Relay, to report the kinds of statistics you're looking for would require [fairly hacky solutions](https://stackoverflow.com/questions/11356330/how-to-get-cpu-usage) since cross-platform languages like Go are designed to hide such details more than expose them... and there'd be no point in trying to do so anyway, because we'd just be reinventing the wheel. In my experience ops people tend to want to use standard widely-used tools that are actually designed for that purpose, rather than looking at some theoretically equivalent stat that can be queried out of an application whose main role is something else.
