### ISSUE TITLE
LaunchDarkly proxy status page displays Client-side ID in plain text

### ISSUE THREAD

**Issue by yj10545** [launchdarkly/ld-relay#129]
I have set-up LD Proxy in AWS env using ECS and a load balancer. I have enabled persistent storage using DynamoDB and auto configuration. Everything works well, however when I used the status page (https://<proxyURL>/status) in the browser I noticed that the client id and the DynamoDB name are displayed in plain text. Is there a way to disable LB Proxy from displaying sensitive info in plain text?

I have used  ENV_DATASTORE_PREFIX=ld-flags-$CID for auto config setting, this causes the client id to display in plain text. If I dont use $CID, I get an error msg - 2021/02/03 22:47:04.503636 ERROR: Configuration error: when using auto-configuration with database storage, database prefix (or, if using DynamoDB, table name) must be specified and must contain "$CID"

**Comment by eli-darkly** [comment]
The client-side ID is not and cannot be a secure credential. It's the one that is used by the browser SDK, so it is trivially easy for anyone using any webapp that uses the LD browser SDK to see that value in request URLs. The reason this isn't considered a problem is that, by design, the only thing anyone can do with the client-side ID is to ask LaunchDarkly to evaluate flag values with it, given some set of user properties; there is no way to use it to see what the flag rules are, or what the allowable user properties might be.

**Comment by eli-darkly** [comment]
As per the documentation: ["The client-side ID is not considered confidential and does not need to be kept a secret."](https://docs.launchdarkly.com/sdk/concepts/client-side-server-side#client-side-id).

**Comment by eli-darkly** [comment]
Maybe I should say that in some cases it may be desirable to limit use of the client-side ID by curious third parties, i.e. if you feel that just knowing whether flag X would be on or off for some range of arbitrary user keys (even without knowing any details of the actual flag rules) would reveal too much about your business logic. That's why there is a [secure mode](https://docs.launchdarkly.com/sdk/client-side/javascript#secure-mode) feature. But the whole reason why such a feature is desirable is that it is, by definition, impossible to keep the client-side ID itself a secret; if it's ever used for its intended purpose (in front-end code) it is no longer secret.
