### ISSUE TITLE
/status endpoint - datastore status should be a top-level object

### ISSUE THREAD

**Issue by asaha123** [launchdarkly/ld-relay#145]
**Is this a support request?**

No.

**Describe the bug**

Currently the `/status` endpoint returns the health status of the persistent store inside an environment object. Thus, if i have two environments configured, the data store status is included in both the environments. I do not think that's correct, since we can only configure [one persistent store](https://github.com/launchdarkly/ld-relay/blob/fc38d2ffb8c27d0ecc0d32bb9ec98dfbac8e9e12/internal/core/relay_core_endpoints_status.go#L34) for launchdarkly relay?

**To reproduce**

Documentation: https://github.com/launchdarkly/ld-relay/blob/v6/docs/persistent-storage.md

**Expected behavior**

```
{
  "environments": {
    "environment1": {
      "sdkKey": "sdk-********-****-****-****-*******99999",
      "envId": "999999999999999999999999",
      "mobileKey": "mob-********-****-****-****-*******99999",
      "status": "connected",
      "connectionStatus": {
        "state": "VALID",
        "stateSince": 10000000
      },      
    "environment2": {
      "sdkKey": "sdk-********-****-****-****-*******99999",
      "envId": "999999999999999999999999",
      "mobileKey": "mob-********-****-****-****-*******99999",
      "status": "connected",
      "connectionStatus": {
        "state": "INTERRUPTED",
        "stateSince": 12000000,
        "lastError": {
          "kind": "NETWORK_ERROR",
          "time": 12000000
        }
      },
    },
},
{
      "dataStoreStatus": {
        "state": "VALID",
        "stateSince": 10000000,
        "database": "dynamodb",
        "dbTable": "env1"
      }
    }
  },
  "status": "healthy",
  "version": "5.11.1",
  "clientVersion": "4.17.2"
}
```

**Additional context**

**Comment by eli-darkly** [comment]
I understand what you're getting at abstractly, but the way the Relay Proxy actually works is a bit different from what you're assuming.

The data store component is not actually just one shared component— there is one for each of the environments, because the Relay Proxy creates a Go SDK instance for each environment and the SDK is what manages both the LaunchDarkly connection and the data store. So a new data store component is created for each environment, with most of its configuration (but not all— see below) copied from the basic Relay Proxy configuration.

The SDK provides the data store status information, and since this is based on whether the SDK has encountered any database errors, it is theoretically possible for the data store status to be different in each SDK instance (that is, maybe the one for environment1 has seen an error, and the one for environment2 has not seen an error because it didn't happen to be trying to do any database things at the moment the database was having a problem).

So, the way the status information is currently presented is accurate in terms of how the Relay Proxy gets that information. And presenting it that way has the advantage that for any given application that is connected, which only cares about one of the environments, it can simply look at the status object for its particular environment and get all the necessary information about whether things are working.

Also, the Relay Proxy's data store status object doesn't _only_ include the data store status that it gets from the SDK; it also includes some of the data store _configuration_. And that is not the same for every environment; the `prefix` property is different for each one. That is important information because if an application is directly accessing the database, it needs to use the appropriate prefix for its environment.

It would still be possible for us to _also_ provide a top-level status which is based on the lowest common denominator of the individual statuses— that is, if any of them are bad, then the top-level status is bad. It would not be able to replace the individual statuses though, because 1. it is still potentially important to know whether the SDK instance for a particular environment has had any problems or not (if environment1 got an error but environment2 didn't, then you can at least be confident that the flag data for environment2 has been updated), and 2. the configured prefix is per-environment.

**Comment by asaha123** [comment]
Got it, thank you. You are right about my wrong assumption. Things are clearer now.
