### ISSUE TITLE
Proxy `/sdk/latest-all` endpoint

### ISSUE THREAD

**Issue by seangatewood** [launchdarkly/ld-relay#169]
**Is your feature request related to a problem? Please describe.**
Following [these docs](https://docs.launchdarkly.com/sdk/features/flags-from-files/), we pull a JSON snapshot from LaunchDarkly's `/sdk/latest-all` endpoint
(`https://app.launchdarkly.com/sdk/latest-all`) for use in internal testing environments.

Per our security requirements, we're actually not supposed to connect to LaunchDarkly directly at all. Thus, we are required to change this and pull this file from our relay proxy instead.

**Describe the solution you'd like**
If possible, the relay proxy should proxy the `/sdk/latest-all` endpoint. (The `/all` endpoint is sub-optimal since that is a streaming endpoint, and the `/sdk/flags` endpoint does not include segment information and is a slightly different json structure.)

**Describe alternatives you've considered**
We could try to find some way to get the first chunk of data from the `/all` streaming endpoint and then cut off the connection.

**Additional context**
(If support is added, we should maybe update [this page](https://github.com/launchdarkly/ld-relay/blob/v6/docs/endpoints.md) too.)

**Comment by eli-darkly** [comment]
This isn't a use case we had heard about before - thanks for bringing it to our attention.

The main reason this endpoint currently isn't implemented in the Relay Proxy is that the endpoint's original purpose in LD wasn't this— it was to support SDKs that are not able to make a streaming connection and need to use polling instead. We hadn't expected anyone to use polling mode in conjunction with the Relay Proxy because it's significantly less efficient in terms of network usage and load-balancing.

Then, when the file data source feature was added to the SDKs, we recommended hitting this endpoint as a convenient way to download existing data, because the JSON schema used for flag data is deliberately the same in all SDK components. We weren't thinking of a case where someone would want to do this indirectly through the Relay Proxy.

It's not impossible to implement, but there are a couple of issues related to its original purpose that make it slightly less straightforward than you might think. If the Relay Proxy is going to support SDK polling mode (again, I understand that's not your use case, but if we implement that endpoint then we are supporting it) then it's important that we replicate the real LD's behavior with regard to HTTP-cacheability. That involves generating and keeping track of Etag headers that are correlated with changes in the flag/segment data. I think it would be unwise for us to add support for this endpoint without doing that part, because then if anyone points an SDK in polling mode at a Relay Proxy instance, they will be downloading their entire environment again every 30 seconds.

**Comment by seangatewood** [comment]
Thank you for your quick responses! My team and I always appreciate it. 🙂

I think for now we'll be able to get away with the workaround I described above, unless you can think of a better way to get the JSON snapshot. (e.g. We're in python for this code, so one other thought is to construct a regular LDClient pointed at our proxy and extract the JSON data from that somehow. 🤷‍♂️)

**Comment by eli-darkly** [comment]
If "the workaround I described above" means calling the streaming `/all` endpoint instead, that is doable. The response from that endpoint is a [Server-Sent Events](https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events) stream, and the first message on the stream should contain the full environment data, as follows: the event name is "put" and the event data is a JSON string `{"data": XXX}` where `XXX` is the same JSON representation that you would get from the polling endpoint (`{"flags": { ... }, "segments": { ... }}`). There are some subtleties and edge cases in implementing SSE correctly, so rather than relying on details of the exact layout of this message in a current Relay Proxy response (e.g. that the lines are separated by `"\n"` and that there is only one `data:` line), it would be best to use an actual SSE client implementation if you're going to do this. So, it's not as straightforward as being able to use the polling endpoint would be, but it's probably somewhat less of a hassle than trying to pull the data out of the SDK.

**Comment by seangatewood** [comment]
Gotcha, that's what I was seeing, but I was unaware of the SSE standard. 🤩 Thank you!
