### ISSUE TITLE
DynamoDB 400kb per-item limit can prevent the relay from serving up-to-date flags

### ISSUE THREAD

**Issue by prydonius** [launchdarkly/ld-relay#173]
**Is this a support request?**
yes

**Describe the bug**
We have LD Relay setup with DynamoDB. We ran into an issue where someone created a Segment in LaunchDarkly with a large set of users, and this caused errors in the LD Relay when writing to DynamoDB:

```
2022/03/16 19:34:51.211358 ERROR: [env: default_production] Failed to store initial
streaming data in data store (failed to write 634 items(s) in batches:
ValidationException: Item size has exceeded the maximum allowed size
```

Per the [docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ServiceQuotas.html#limits-items), DynamoDB has a 400kb per-item limit that cannot be exceeded.

The result was that the LD Relay served stale feature flag variations whilst this error was happening as it wasn't able to update DynamoDB with newer flag variations. We were able to temporarily resolve the issue by dropping the large segment and breaking it up into multiple smaller segments.

**To reproduce**
Create a segment or feature flag with a large list of users that is > 400kb when encoded.

**Expected behavior**
The LD Relay should still be able to serve feature flags (e.g. from memory) if it can't write to the data store. Additional logs on the failure would also be useful to help identify the flags that are over the limit.

Given this is a hard limit, it should be documented when using the DynamoDB storage backage.

**Logs**
See above

**SDK version**
Erlang `1.1.2`
Kotlin `5.0.3`
Golang relay proxy `ld-relay v5`
Golang `go-server-sdk.v4`
Python `7.0.1`

**Language version, developer tools**
For instance, Go 1.11 or Ruby 2.5.3. If you are using a language that requires a separate compiler, such as C, please include the name and version of the compiler too.

**OS/platform**
For instance, Ubuntu 16.04, Windows 10, or Android 4.0.3. If your code is running in a browser, please also include the browser type and version.

**Additional context**

**Comment by eli-darkly** [comment]
I think the issues here boil down to:
1. It'd be desirable to decouple the actions of "persist this update in memory, and pass it on to SDK clients" and "persist this update in the database" a little more so that database errors in general (not just related to the DynamoDB data size limit) don't block the rest of the processing of the update.
2. The DynamoDB data size issue should be documented more prominently.

I agree on both points, but there are some design issues that make the first one a little less straightforward than you might expect. The short version is that this logic is not so much implemented in the Relay Proxy code as it is in the LaunchDarkly Go SDK code, which the Relay Proxy relies on heavily for the tasks of getting and storing flag data, so (I think) it's not something we could address strictly through code changes in this service. And the required changes would probably be substantial enough that they'd need to be done in a new major version release of the SDK. We are already planning to do such a release later this year for other unrelated new features, and we're also using that as an opportunity to make other design improvements, so it's possible that we might be able to address this as part of that; however, I can't provide a more specific time frame, since the other feature work is the current priority.

One thing we might be able to improve slightly in the meantime is the error logging. I'm not sure exactly what the log output currently looks like when an error like this happens— I _think_ it does include a DynamoDB message that specifically mentions the data size limit, but maybe it does not say which specific flag or segment was involved, in which case adding such information would at least make the problem easier to track down.

As for the documentation, I'll bring it up with the docs team in terms of maybe making some database-related information more prominent in the online pages for the Relay Proxy— right now I believe it links to the data storage page in the SDK documentation, and the DynamoDB section there does have a warning message about the data size limit, but that requires drilling down to find it.

**Comment by eli-darkly** [comment]
After writing that, I realized that my answer was a little off base in terms of the details. That doesn't necessarily matter because the conclusion is still the same: to really address this well, we will need to make some SDK design changes. But just FYI, here's a more accurate description.

There is already some logic in the Go SDK, and therefore in Relay, to address the issue you're talking about in some cases. Specifically, if you tell it that the in-memory cache in front of DynamoDB should _never expire_, then I believe it will do more or less what you want it to do: that is, in the case of a database error during an update, Relay would still keep the new data in memory and use it for evaluations. The way you would configure this is to set the cache TTL to a negative number— there's no way you would have known that from the Relay docs, we need to update those, currently it is only explained in the SDK docs. But if the cache TTL is a finite positive number, then it deliberately does _not_ update the in-memory cache in case of a database error, because then as soon as the cached item expired, you would see an unexpected change in state as the new information disappeared.

The more fundamental problem is that currently it does not have a way to distinguish between different kinds of database errors. The error-handling logic was all written with the premise that a database error probably represents some kind of transient server problem or connectivity problem, rather than it being a problem with the data we're trying to store. So, whenever there's any database error on an update, it enters a state where it periodically retries, hoping that the database is working again. And in this particular case that's very undesirable, because the update cannot possibly succeed so the retries would be pointlessly adding traffic that would count against your DynamoDB throughput limits. So, to make this smarter, we will need to change how the SDK communicates with the data storage component. Since the interface for that component is public (so people can write their own integrations), that is a breaking change— and therefore the conclusion is the same: it would have to be done in a new major version release of the SDK.

**Comment by eli-darkly** [comment]
This is mitigated in the [v6.7.3](https://github.com/launchdarkly/ld-relay/releases/tag/v6.7.3) release. The Relay Proxy is still not able to store an item >400KB (that is, we have not implemented a new schema that would let us break them up), but the failure mode is now as follows:

* It logs (at ERROR level) a message indicating which flag or segment was too big.
* That individual data item does not get written to DynamoDB (it will not even attempt to, so it won't affect your DynamoDB throughput).
* All other data items still do get written, unlike previously when it could have failed to store a whole batch of items if one item was too big.
* Previously this kind of error could cause it to enter a retry mode where it would keep trying to rewrite the item at intervals, even though that could never succeed. This no longer happens.
* Any clients that are already connected (in proxy mode, that is, via HTTP) at the time a too-large update arrives will still receive the update from Relay.
* For clients that connect later, whether the too-large item is still available via in-memory caching will depend on the cache settings. If there is a finite cache TTL (the default), then the item will still expire out of memory at some point and after that point, what will be served is the last version of that item (if any) that _did_ get stored in the database. If the cache TTL has been set to a negative number, meaning "don't ever expire" (i.e. the Relay Proxy will never read from the database, only write to it, except if it has to restart), then the too-large item remains available in memory.

**Comment by prydonius** [comment]
Thanks @eli-darkly, excited to try this release out, this definitely will give us a lot more confidence in case we run into this again!
