### ISSUE TITLE
endpoints description

### ISSUE THREAD

**Issue by anicolaspp** [launchdarkly/ld-relay#26]
Can we get in the docs a description of the available endpoints?

**Comment by atrakh** [comment]
Hi @anicolaspp,

Thanks for reaching out! Typically, expected usage of the relay would be to proxy LaunchDarkly SDK connections to the relay, rather than interacting with relay endpoints manually. Thus, the relay proxies LaunchDarkly endpoints consumed by our SDKs, which are subject to change.

Exclusions to this rule include the [status](https://github.com/launchdarkly/ld-relay#status-endpoint) and [flag-evaluation](https://github.com/launchdarkly/ld-relay#status-endpoint), which are documented in the readme. Excluding those cases, SDK connectivity is described in the following resources:
https://github.com/launchdarkly/ld-relay#what-is-it
https://github.com/launchdarkly/ld-relay#mobile-and-client-side-flag-evaluation

While we're not completely opposed to documenting all relay endpoints, we'd like to first get a better idea of how this will help. Can you tell me a little more about your use-case for the relay?

**Comment by ashanbrown** [comment]
@anicolaspp The latest README At https://github.com/launchdarkly/ld-relay/blob/master/README.md now has a list of all currently supported endpoints.  We will endeavor to keep it up to date.   Thanks for your interest in this project.
