### ISSUE TITLE
disableInternalUsageMetrics has been removed in relay v8

### ISSUE THREAD

**Issue by husseinsakr** [launchdarkly/ld-relay#264]
**Is your feature request related to a problem? Please describe.**
In version 8 of `ld-relay`, `disableInternalUsageMetrics` was deprecated. We currently use the launchdarkly relay proxy with it enabled to avoid unnecessary network data sent to launchdarkly. Is it possible to add it back?

**Describe the solution you'd like**
Re-adding `disableInternalUsageMetrics` option

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cwaldren-ld** [comment]
Hi @husseinsakr ,

Previously the data collected by the Relay Proxy and sent to LaunchDarkly was only used for internal diagnostic purposes. Because this data wasn’t critical, LaunchDarkly provided a `disableInternalUsageMetric` Relay Proxy configuration option to allow customers to disable the data publication.

In the near future, this data will have increased importance on the LaunchDarkly platform. As a result, LaunchDarkly removed the option for customers to disable this data’s publication.

**Comment by husseinsakr** [comment]
Thank you @cwaldren-ld 

> In the near future, this data will have increased importance on the LaunchDarkly platform. As a result, LaunchDarkly removed the option for customers to disable this data’s publication.

How will this effect the launchdarkly relay proxy in offline mode in the future?  Specifically your mentioning of "this data will have increased importance on the LaunchDarkly platform". For our fedramp solution, we use the relay proxy in offline mode which today enables `disableInternalUsageMetric`.

**Comment by cwaldren-ld** [comment]
Offline mode will continue to be supported. In offline mode, the internal usage metrics will not be sent to LaunchDarkly.

At this time, the change only affects the default behavior of Relay (_not_ offline), which is to connect to LaunchDarkly for flag data.

To be clear, offline mode and `disableInternalUsageMetric` could be configured independently and control different things. Offline mode means no connections to LaunchDarkly at all, whereas `disableInternalUsageMetric` could be used even when connecting to LaunchDarkly to receive flag data.

**Comment by husseinsakr** [comment]
Thank you @cwaldren-ld !
