### ISSUE TITLE
Expected Resource Requirements (CPU & Memory) for use in Kubernetes

### ISSUE THREAD

**Issue by BrianChristie** [launchdarkly/ld-relay#57]
When running in a container orchestrator such as Kubernetes, it is required to list explicit resource requirements for vCPU and Memory limits.

Can you provide guidance on what the resource requirements are? And do these increase linearly with request volume?

Thanks!

**Comment by bwoskow-ld** [comment]
Hi Brian,

Apologies for the very delayed response!

Are you still looking for guidance on resource requirements? We haven't measured the resource requirements recently so I can't get that information for you right now, but we can look into this if it would be helpful.

Ben

**Comment by ccgagnon** [comment]
Hi Ben,

I would like to have this information too. It would be helpful. :)

Thanks!

**Comment by bwoskow-ld** [comment]
For customers using AWS we generally recommend that they deploy LD Relay to an m4.xlarge instance. Per the information specified on https://aws.amazon.com/ec2/instance-types/, this means a vCPU of 4 and memory of 16GiB. I recommend that you start with those values, monitor your resource utilization, and then scale appropriately based on your use. 

I want to point out that in general, LD Relay's memory and CPU utilization are typically low, and that the application is much more likely to be constrained by network performance. The reason that we suggest m4.xlarge over m4.large is due to the instance's higher networking performance (not because of the increased vCPU or memory capabilities), and as a result, the memory and CPU actually utilized by LD Relay may in fact be significantly lower than what's available per the m4.xlarge spec.
