### ISSUE TITLE
Not able to import this as a library

### ISSUE THREAD

**Issue by nikunjy** [launchdarkly/ld-relay#99]
I can't even clone your repo and `make` 
```
internal/events/event-relay.go:19:2: use of internal package gopkg.in/launchdarkly/ld-relay.v5/internal/util not allowed
internal/events/event_publisher.go:16:2: use of internal package gopkg.in/launchdarkly/ld-relay.v5/internal/version not allowed
internal/metrics/events_exporter.go:9:2: use of internal package gopkg.in/launchdarkly/ld-relay.v5/internal/events not allowed
```

**Comment by eli-darkly** [comment]
For the failure of `make`, it's hard to say what the issue is without knowing a little more, like what environment you're trying to build it in (OS, Go version, etc.), and _exactly_ how you checked it out (like, are you in a directory within GOPATH and what is it called).

For the other issue mentioned in the PR title, you haven't provided any information at all. How were you importing it? What was the error?

**Comment by nikunjy** [comment]
I am importing it in a project that is using go module. 
`go get github.com/launchdarkly/ld-relay`

It changes my `go.mod`  and the relevant changes for this conversation are
```
 gopkg.in/launchdarkly/ld-relay.v5 v5.0.0-20200810170413-f69cc4db12f3 // indirect
github.com/launchdarkly/ld-relay v0.0.0-20200810170413-f69cc4db12f3
github.com/launchdarkly/gcfg v0.0.0-20160218190638-83c3f001aeeb // indirect
 github.com/launchdarkly/go-ntlm-proxy-auth v1.0.1 // indirect
```

When I try to build my stuff it throws that error `use of internal package ... `

**Comment by nikunjy** [comment]
I think I figured it out I have to do this 
```go get gopkg.in/launchdarkly/ld-relay.v5```
I also had to do this 
```go get gopkg.in/launchdarkly/go-server-sdk.v4```

**Comment by eli-darkly** [comment]
Ah - yes, the problem was due to using the `github.com` import path rather than `gopkg.in`. The current readme text about importing it as a library doesn't call that out, although if you look at the source code you can see that it's using the `gopkg.in` path for all of its internal imports. We've been rewriting the docs for the next release and this will be clearer in the future - sorry.

I'm not sure why you would need to do a separate `go get` for `go-server-sdk.v4`, though; I would've expected that to be pulled in automatically as a transitive dependency.

**Comment by nikunjy** [comment]
https://github.com/launchdarkly/ld-relay/pull/100
Added a PR for calling it out.

**Comment by sumuis** [comment]
https://www.google.com/search?q=internal%2Fevents%2Fevent-relay.go%3A19%3A2%3A+use+of+internal+package+gopkg.in%2Flaunchdarkly%2Fld-relay.v5%2Finternal%2Futil+not+allowed&oq=internal%2Fevents%2Fevent-relay.go%3A19%3A2%3A+use+of+internal+package+gopkg.in%2Flaunchdarkly%2Fld-relay.v5%2Finternal%2Futil+not+allowed&aqs=chrome..69i57j69i58.2455j0j4&sourceid=chrome&ie=UTF-8

**Comment by sumuis** [comment]
https://docs.launchdarkly.com/home/getting-started

**Comment by eli-darkly** [comment]
Relay 6.x has been out since last month; it includes a fair amount of new functionality, and the code organization has been greatly improved including making it usable as a module. If you haven't already, you may want to try migrating to this version. Note that the import path is now `github.com/launchdarkly/ld-relay.v6`, and there have been changes to the public API which you can see [here](https://pkg.go.dev/github.com/launchdarkly/ld-relay/v6@v6.0.0-20201008200304-9e81df09914d/relay) and [here](https://pkg.go.dev/github.com/launchdarkly/ld-relay/v6@v6.0.0-20201008200304-9e81df09914d/config).
